/**
 * N64AnimExporter.ts
 * Bakes AnimClip keyframes to N64 tiny3d–compatible C headers.
 *
 * Output is a .h file containing fixed-point animation data arrays
 * that the N64 runtime links directly — no dynamic allocation needed.
 *
 * Pipeline:
 *  AnimClip → sample at 30fps → convert to 16.16 fixed-point → emit C arrays
 *
 * The generated header is included by the entity's .c file and
 * consumed by tiny3d's T3DAnim_create() / T3DAnim_update() API.
 */

import {
  type AnimClip,
  type AnimTrack,
  type TrackProperty,
  evaluateTrack,
} from './AnimationClip';

// ─── Constants ────────────────────────────────────────────────────────────────

/** N64 runtime sample rate — 30fps matches the RSP mixer tick. */
const SAMPLE_RATE_FPS = 30;

/** 16.16 fixed-point scale factor. */
const FIXED_POINT_SCALE = 65536;

/** Maximum frames per clip (memory budget: ~4 seconds at 30fps). */
const MAX_FRAMES = 120;

/** Rotation values are stored as 0–65535 mapping to 0–360 degrees. */
const ROTATION_SCALE = 65536 / 360;

// ─── Export result ────────────────────────────────────────────────────────────

export interface ExportResult {
  /** The generated C header contents. */
  header: string;
  /** The sanitized identifier used in generated symbol names. */
  identifier: string;
  /** Total frame count. */
  frameCount: number;
  /** Approximate RDRAM usage in bytes. */
  sizeBytes: number;
  /** Warnings about budget or precision. */
  warnings: string[];
}

// ─── Exporter ─────────────────────────────────────────────────────────────────

/**
 * Export an AnimClip to a C header string for the N64 runtime.
 *
 * @param clip The animation clip to export
 * @returns ExportResult containing the generated header and metadata
 */
export function exportClipToN64(clip: AnimClip): ExportResult {
  const warnings: string[] = [];
  const id = sanitizeIdentifier(clip.name);
  const unclampedFrameCount = Math.ceil(clip.duration * SAMPLE_RATE_FPS);
  const frameCount = Math.min(unclampedFrameCount, MAX_FRAMES);

  if (unclampedFrameCount > MAX_FRAMES) {
    warnings.push(
      `Clip "${clip.name}" clamped to ${MAX_FRAMES} frames (${(MAX_FRAMES / SAMPLE_RATE_FPS).toFixed(1)}s). ` +
      `Original duration: ${clip.duration.toFixed(2)}s.`,
    );
  }

  if (clip.tracks.length === 0) {
    warnings.push(`Clip "${clip.name}" has no tracks — header will be empty.`);
  }

  // Bake each track
  const bakedTracks = clip.tracks.map(track =>
    bakeTrack(track, frameCount, clip.duration),
  );

  // Calculate size
  // Each frame for a track stores 3 int32 values = 12 bytes
  const sizeBytes = clip.tracks.length * frameCount * 3 * 4;

  // Generate header
  const header = generateHeader(id, clip, bakedTracks, frameCount);

  return { header, identifier: id, frameCount, sizeBytes, warnings };
}

// ─── Internals ────────────────────────────────────────────────────────────────

interface BakedTrack {
  targetNode: string;
  property:   TrackProperty;
  /** Fixed-point samples: frameCount × 3 values. */
  samples:    number[];
}

function bakeTrack(
  track: AnimTrack,
  frameCount: number,
  duration: number,
): BakedTrack {
  const samples: number[] = [];

  for (let f = 0; f < frameCount; f++) {
    // Sample at fixed SAMPLE_RATE_FPS so each frame corresponds to a 1/30s tick.
    const t = Math.min(f / SAMPLE_RATE_FPS, duration);
    const val = evaluateTrack(track, t);

    if (track.property === 'rotation') {
      // Convert degrees → 0..65535 range
      samples.push(
        Math.round((((val[0] % 360) + 360) % 360) * ROTATION_SCALE),
        Math.round((((val[1] % 360) + 360) % 360) * ROTATION_SCALE),
        Math.round((((val[2] % 360) + 360) % 360) * ROTATION_SCALE),
      );
    } else {
      // Position/scale → 16.16 fixed-point
      samples.push(
        Math.round(val[0] * FIXED_POINT_SCALE),
        Math.round(val[1] * FIXED_POINT_SCALE),
        Math.round(val[2] * FIXED_POINT_SCALE),
      );
    }
  }

  return { targetNode: track.targetNode, property: track.property, samples };
}

function generateHeader(
  id: string,
  clip: AnimClip,
  tracks: BakedTrack[],
  frameCount: number,
): string {
  const guard = `PYRITE64_ANIM_${id.toUpperCase()}_H`;
  const lines: string[] = [];

  lines.push(`/**`);
  lines.push(` * Auto-generated by Pyrite64 N64AnimExporter`);
  lines.push(` * Clip: "${clip.name}" | Duration: ${clip.duration.toFixed(3)}s | Frames: ${frameCount}`);
  lines.push(` * DO NOT EDIT — regenerate from the editor.`);
  lines.push(` */`);
  lines.push(``);
  lines.push(`#ifndef ${guard}`);
  lines.push(`#define ${guard}`);
  lines.push(``);
  lines.push(`#include <stdint.h>`);
  lines.push(``);
  lines.push(`#define ANIM_${id.toUpperCase()}_FRAME_COUNT  ${frameCount}`);
  lines.push(`#define ANIM_${id.toUpperCase()}_FPS           ${SAMPLE_RATE_FPS}`);
  lines.push(`#define ANIM_${id.toUpperCase()}_LOOP          ${clip.loop ? 1 : 0}`);
  lines.push(`#define ANIM_${id.toUpperCase()}_TRACK_COUNT   ${tracks.length}`);
  lines.push(``);

  for (let ti = 0; ti < tracks.length; ti++) {
    const bt = tracks[ti];
    const arrayName = `anim_${id}_track${ti}_${bt.targetNode}_${bt.property}`;
    const comment =
      bt.property === 'rotation'
        ? '/* 0..65535 → 0..360° */'
        : '/* 16.16 fixed-point */';

    lines.push(`${comment}`);
    lines.push(
      `static const int32_t ${sanitizeIdentifier(arrayName)}[${frameCount}][3] = {`,
    );

    for (let f = 0; f < frameCount; f++) {
      const base = f * 3;
      const x = bt.samples[base];
      const y = bt.samples[base + 1];
      const z = bt.samples[base + 2];
      const comma = f < frameCount - 1 ? ',' : '';
      lines.push(`  { ${x}, ${y}, ${z} }${comma}`);
    }

    lines.push(`};`);
    lines.push(``);
  }

  lines.push(`#endif /* ${guard} */`);
  return lines.join('\n');
}

/**
 * Convert a clip/node name to a valid C identifier.
 * Replaces non-alphanumeric chars with underscores and strips leading digits.
 */
function sanitizeIdentifier(name: string): string {
  let id = name.replace(/[^a-zA-Z0-9_]/g, '_');
  // C identifiers cannot start with a digit
  if (/^[0-9]/.test(id)) id = '_' + id;
  return id;
}
